### ISSUE TITLE
TypeError in Homepage

### ISSUE THREAD

**Issue by Feramance** [LionCityGaming/recently-added#2]
Hi,

I keep getting a TypeError on Homepage using the setup provided, not sure what's wrong either, except maybe the all endpoint having lists within lists. Currently the all endpoint return the following:

```
{"Anime":[{"date_added":"May 23","title":"KonoSuba: An Explosion on This Wonderful World!"},{"date_added":"Apr 18","title":"The Grimm Variations"},{"date_added":"Apr 13","title":"THE NEW GATE"},{"date_added":"Apr 01","title":"Cyberpunk: Edgerunners"},{"date_added":"Apr 01","title":"The Demon Sword Master of Excalibur Academy"},{"date_added":"Apr 01","title":"The Aristocrat\u2019s Otherworldly Adventure: Serving Gods Who Go Too Far"},{"date_added":"Apr 01","title":"Rent-a-Girlfriend"},{"date_added":"Apr 01","title":"Our Dating Story: The Experienced You and The Inexperienced Me"},{"date_added":"Apr 01","title":"Oshi no Ko"},{"date_added":"Apr 01","title":"\u014cban Star-Racers"}],"Movies":[{"date_added":"Jun 05","title":"Gandhi"},{"date_added":"Jun 04","title":"Pinocchio"},{"date_added":"Jun 04","title":"White Bird"},{"date_added":"Jun 04","title":"Dumbo"},{"date_added":"Jun 04","title":"Bambi II"},{"date_added":"Jun 04","title":"Bambi"},{"date_added":"Jun 04","title":"101 Dalmatians 2: Patch's London Adventure"},{"date_added":"Jun 03","title":"The Wizard of Oz"},{"date_added":"Jun 03","title":"We Are Your Friends"},{"date_added":"Jun 03","title":"One Hundred and One Dalmatians"}],"Series":[{"date_added":"Jun 05","title":"The Acolyte"},{"date_added":"Jun 04","title":"Xiaolin Showdown"},{"date_added":"Jun 03","title":"Echo"},{"date_added":"Jun 01","title":"The Good Doctor"},{"date_added":"May 30","title":"Star Trek: Short Treks"},{"date_added":"May 17","title":"Clarkson's Farm"},{"date_added":"May 17","title":"The Boys"},{"date_added":"May 15","title":"For All Mankind"},{"date_added":"May 15","title":"Marvel's Iron Fist"},{"date_added":"May 15","title":"The Grand Tour (2016)"}]}
```

The library endpoints return a list of values unlike the all endpoint however, neither endpoint is working when using the provided `customapi` mapping and `custom css` code. Is there anything else I'm missing?

```
    - Recently Added:
        id: recentlyadded
        icon: plex.png
        widget:
            type: customapi
            url: http://recently-added:8080/api/series
            display: list
            mappings:
              - field:
                    0: title
                additionalField:
                    field:
                    0: date_added
              - field:
                    1: title
                additionalField:
                    field:
                    1: date_added
```

```
